##########################################################################################################################
# File automatically-generated by tool: AT32 Work Bench V1.2.04
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
# ------------------------------------------------

######################################
# target
######################################
TARGET = openlog


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES = \
project/src/main.c \
project/src/openlog.c \
project/src/openlog_fs.c \
project/src/sd_spi.c \
project/src/diskio.c \
project/src/syscalls.c \
project/src/sysmem.c \
project/src/at32f421_wk_config.c \
project/src/at32f421_int.c \
project/src/wk_system.c \
project/src/wk_spi.c \
project/src/wk_usart.c \
libraries/cmsis/cm4/device_support/system_at32f421.c \
third_party/FatFs/src/ff.c \
libraries/drivers/src/at32f421_crm.c \
libraries/drivers/src/at32f421_cmp.c \
libraries/drivers/src/at32f421_tmr.c \
libraries/drivers/src/at32f421_ertc.c \
libraries/drivers/src/at32f421_gpio.c \
libraries/drivers/src/at32f421_i2c.c \
libraries/drivers/src/at32f421_usart.c \
libraries/drivers/src/at32f421_pwc.c \
libraries/drivers/src/at32f421_adc.c \
libraries/drivers/src/at32f421_spi.c \
libraries/drivers/src/at32f421_dma.c \
libraries/drivers/src/at32f421_debug.c \
libraries/drivers/src/at32f421_flash.c \
libraries/drivers/src/at32f421_crc.c \
libraries/drivers/src/at32f421_wwdt.c \
libraries/drivers/src/at32f421_wdt.c \
libraries/drivers/src/at32f421_exint.c \
libraries/drivers/src/at32f421_misc.c \
libraries/drivers/src/at32f421_scfg.c \

# ASM sources
ASM_SOURCES = \
startup_at32f421.s \

# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
HOST_CC ?= gcc
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=soft

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_STDPERIPH_DRIVER \
-DAT32F421G8U7


# AS includes
AS_INCLUDES =

# C includes
C_INCLUDES = \
-Iproject/inc \
-Ithird_party/FatFs/src \
-Ilibraries/drivers/inc \
-Ilibraries/cmsis/cm4/core_support \
-Ilibraries/cmsis/cm4/device_support \


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = AT32F421x8_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir -p $@

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

host-test: tests/openlog_fs_test
	./tests/openlog_fs_test

tests/openlog_fs_test: tests/openlog_fs_test.c project/src/openlog_fs.c project/inc/openlog_fs.h
	$(HOST_CC) -std=c11 -Wall -Wextra -Werror -DOPENLOG_FS_USE_RAMDISK_TEST -Iproject/inc tests/openlog_fs_test.c project/src/openlog_fs.c -o $@
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
